version: '3.3'
services:
  post_db:
    env_file: .env
    image: mongo:${MONGO_IMAGE_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
  ui:
    env_file: .env
    image: ${USER_NAME}/ui:${UI_IMAGE_VERSION}
    ports:
      - ${APP_PORT}:${APP_PORT}/tcp
    networks:
      - front_net
  post:
    env_file: .env
    image: ${USER_NAME}/post:${POST_IMAGE_VERSION}
    networks:
      - back_net
      - front_net
  comment:
    env_file: .env
    image: ${USER_NAME}/comment:${COMMENT_IMAGE_VERSION}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
  front_net:

